version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5174:5174"
    environment:
      - VITE_API_URL=http://localhost:5001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SECRET_KEY=your_secret_key_here
    volumes:
      - ./backend:/app
      - /app/venv 